### ISSUE TITLE
Thinking how this could be usefull

### ISSUE THREAD

**Issue by ldijkman** [foxabilo/ESP32_ChatGPT#4]
Thinking how this could be usefull

playing with ace editor
because i found that years ago in the esp ESP FSBrowser example

but i see no way how your ESP chat can be usefull yet

greet luberth

treid your html, looks nice
did not try it on a ESP32 Yet

![Screenshot from 2023-11-19 06-46-02](https://github.com/foxabilo/ESP32_ChatGPT/assets/45427770/510c24f6-40e1-4683-9ae5-0cb5ca87e403)

**Comment by foxalabs** [comment]
Sorry for the late reply, been swamped with work. 

This library is really meant as a demonstrator to show how to connect to the OpenAI API endpoint and format an API call to send a prompt to the model and get the response back. The response obtained from the API will then be displayed.
